executable = condor_mytask.sh
arguments = $(ProcId)
output                = mytask.$(ClusterId).$(ProcId).out
error                 = mytask.$(ClusterId).$(ProcId).err
log                   = mytask.$(ClusterId).log

# Send the job to Held state on failure.
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

# Periodically retry the jobs every 10 minutes, up to a maximum of 5 retries.
periodic_release =  (NumJobStarts < 3) && ((CurrentTime - EnteredCurrentStatus) > 600)

+JobFlavour="microcentury"
queue 181

